config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users

  authenticate :user do
    mount Sidekiq::Web => "/sidekiq"
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "home#index"

  post "/generate/event", to: "home#event"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  # Storing simple counter in session to display on UI
  def index
    # Initialize counter
    if session[:event_counter].nil?
      session[:event_counter] = {"a" => 0, "b" => 0}
    end

    @counter = session[:event_counter]

    render
  end

  def event
    begin
      event = params[:event]

      if event == "a" || event == "b"
        EventCreationJob.perform_later({event: event, email: current_user.email})

        # Increment corresponding counter
        session[:event_counter][event] = session[:event_counter][event] + 1
        @counter = session[:event_counter]

        flash.notice = "Enqueued job for Event #{event.upcase}"
      end
    rescue => ex
      flash.alert = "An error occurred!"
    end

    respond_to do |format|
      format.html { render 'index'}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<% if user_signed_in? %>
  	<!-- Main container -->
	<nav class="level">
	  <!-- Left side -->
	  <div class="level-left">
	    <div class="level-item title is-4">
	      Welcome <%= current_user.email %>
	    </div>
	  </div>

	  <!-- Right side -->
	  <div class="level-right">
	    <p class="level-item">
			<%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "button is-success"%>
	    </p>
	  </div>
	</nav>


	<div class="columns content has-text-centered">
		<div class="column">
			<%= button_to "Generate Event A", generate_event_path, params: {event: "a"}, method: :post, remote: true, class: "button block is-info is-medium is-fullwidth" %>
			<p>Event A counter: <%= @counter["a"] %></p>
		</div>
		<div class="column">
			<%= button_to "Generate Event B", generate_event_path, params: {event: "b"}, method: :post, remote: true, class: "button block is-warning is-medium is-fullwidth"%>
			<p>Event B counter: <%= @counter["b"] %></p>
		</div>
	</div>

<% else %>
  	<%= button_to "Sign in", new_user_session_path, method: :get %> 
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoffeeBeans Assignment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
  </head>

  <body>
    <section class="hero is-primary">
      <div class="hero-body">
        <div class="container">
          <p class="title">
            CoffeeBeans Assignment
          </p>
          <p class="subtitle">
            A simple web application to create events and send email notifications.
          </p>
        </div>
      </div>
    </section>

    <section class="section is-medium">
      <div class="container">

        <% if notice.present? %>
          <div class="columns">
            <div class="column">
              <div class="notification is-success is-light">
                <button class="delete" onclick="this.parentElement.style.display='none'"></button>
                <%= notice %>
              </div>
            </div>
          </div>
        <% end %>

        <% if alert.present? %>
          <div class="columns">
            <div class="column">
              <div class="notification is-danger is-light">
                <button class="delete" onclick="this.parentElement.style.display='none'"></button>
                <%= alert %>
              </div>
            </div>
          </div>
        <% end %>

        <div class="columns is-centered">
          <div class="column has-background-grey-lighter">
            <div class="content is-normal">
              <%= yield %>
            </div>
          </div>
        </div>

      </div>
    </section>

    <footer class="footer">
      <div class="content has-text-centered">
        <p>
          Submitted by <strong>Deepak Sharma</strong> | Ruby <strong><%= RUBY_VERSION %></strong> | Rails <strong><%= Rails::VERSION::STRING %></strong>
        </p>
      </div>
    </footer>
  </body>
</html>